# Generated by Django 4.1.3 on 2022-11-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_person_id_alter_person_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfts',
            name='NFTHash',
            field=models.CharField(max_length=46, verbose_name='Хэш код HFT'),
        ),
    ]
