# Generated by Django 4.1.3 on 2022-11-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_nfts_nfthash'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Cost',
            field=models.FloatField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Email',
            field=models.TextField(default=1, unique=True, verbose_name='Адрес почты пользователя'),
            preserve_default=False,
        ),
    ]
