# Generated by Django 4.1.3 on 2022-11-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_history_cost_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Login',
        ),
        migrations.AlterField(
            model_name='history',
            name='Cost',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
