# Generated by Django 4.1.3 on 2022-11-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_person_login_alter_history_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Email',
            field=models.CharField(max_length=256, unique=True, verbose_name='Адрес почты пользователя'),
        ),
    ]
