# Generated by Django 4.1.3 on 2022-11-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfts',
            name='NFTCost',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='nfts',
            name='NFTOwner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Owner', to='API.person', verbose_name='Владелец'),
            preserve_default=False,
        ),
    ]
