# Generated by Django 4.1.3 on 2022-11-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_nfts_nftcost_nfts_nftowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfts',
            name='NFTOwner',
            field=models.ForeignKey(db_column='UserAddress', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Owner', to='API.person', verbose_name='Владелец'),
        ),
    ]
