# Generated by Django 4.1.3 on 2022-11-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_nfts_nftowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfts',
            name='NFTName',
            field=models.CharField(default=None, max_length=31, verbose_name='Имя картинки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nfts',
            name='NFTHash',
            field=models.CharField(max_length=46, verbose_name='Хэш код NFT'),
        ),
    ]
