# Generated by Django 4.1.3 on 2022-11-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_nfts_nftname_alter_nfts_nfthash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NFTs',
            new_name='Nft',
        ),
    ]
