# Generated by Django 4.1.3 on 2022-11-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_alter_nft_nftowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='NFTHash',
            field=models.CharField(max_length=46, unique=True, verbose_name='Хэш код NFT'),
        ),
    ]
