# Generated by Django 4.1.3 on 2022-11-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0017_alter_nft_nfthash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="Cost",
        ),
        migrations.RemoveField(
            model_name="history",
            name="TransferNFTHash",
        ),
        migrations.AddField(
            model_name="history",
            name="NftInfo",
            field=models.ForeignKey(
                db_column="NFTHash",
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="info",
                to="API.nft",
                verbose_name="Информация",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="history",
            name="UserAddressFrom",
            field=models.ForeignKey(
                db_column="UserAddress",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="UserFrom",
                to="API.person",
                verbose_name="Продавец",
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="UserAddressTo",
            field=models.ForeignKey(
                db_column="Email",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="UserTo",
                to="API.person",
                verbose_name="Покупатель",
            ),
        ),
    ]
