# Generated by Django 4.1.3 on 2022-11-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0019_alter_history_nftinfo_alter_history_useraddressfrom_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="NftInfo",
        ),
        migrations.AddField(
            model_name="history",
            name="NFTCost",
            field=models.FloatField(default=0, verbose_name="Цена"),
        ),
        migrations.AddField(
            model_name="history",
            name="NFTHash",
            field=models.CharField(default=0, max_length=46, verbose_name="Хэш НФТ"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="history",
            name="UserAddressFrom",
            field=models.CharField(max_length=42, verbose_name="Продавец"),
        ),
        migrations.AlterField(
            model_name="history",
            name="UserAddressTo",
            field=models.CharField(max_length=42, verbose_name="Покупатель"),
        ),
    ]
