# Generated by Django 4.1.3 on 2022-11-28 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0020_remove_history_nftinfo_history_nftcost_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="NFTCost",
            new_name="Cost",
        ),
        migrations.RemoveField(
            model_name="history",
            name="NFTHash",
        ),
        migrations.AddField(
            model_name="history",
            name="TransferNFTHash",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="API.nft",
                verbose_name="Продаваемая API",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="history",
            name="UserAddressFrom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="UserFrom",
                to="API.person",
                verbose_name="Продавец",
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="UserAddressTo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="UserTo",
                to="API.person",
                verbose_name="Покупатель",
            ),
        ),
    ]
