# Generated by Django 4.1.3 on 2022-11-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0021_rename_nftcost_history_cost_remove_history_nfthash_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="TransferNFTHash",
            new_name="NFTInfo",
        ),
        migrations.RemoveField(
            model_name="history",
            name="Cost",
        ),
    ]
