# Generated by Django 4.1.3 on 2022-11-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='UserAddress',
            field=models.CharField(max_length=42, unique=True, verbose_name='Адрес кошелька пользователя'),
        ),
    ]
